name: Publish

on:
  push:
    branches:
      - master

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - uses: docker/setup-buildx-action@v1
    - name: Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: cfcontainerizationbot
        password: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
    - name: get shortsha
      id: vars
      run: |
       echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: "ghcr.io/cloudfoundry-incubator/brain-tests:g${{ steps.vars.outputs.sha_short }}"
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
